AllCops:
  TargetRubyVersion: 2.4.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 35

Metrics/LineLength:
  AllowURI: true
  Max: 120

Metrics/MethodLength:
  Max: 15
