AllCops:
  TargetRubyVersion: 2.6.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 35

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Enabled: false
