#!/bin/bash

REALPATH=$(cd $(dirname "$0")/.. && pwd)
export RACK_ENV="test"

bundle exec ruby -W2 ${REALPATH}/test/test.rb  "$@"

if [ $? -eq 0 ] && [ $# -eq 0 ]; then
  echo
  echo "==> Rubocop…"
  bundle exec rubocop --config ${REALPATH}/.rubocop.yml --parallel
fi
