#!/bin/bash

REALPATH=$(cd $(dirname "$0")/.. && pwd)
export RACK_ENV="test"

bundle exec ruby ${REALPATH}/test/test.rb  "$@"

if [ $? -eq 0 ]; then
  echo
  echo "==> Rubocop…"
  rubocop --config ${REALPATH}/.rubocop.yml --parallel
fi
