name: Scheduled

on:
  schedule:
    - cron: 11 * * * *

jobs:
  hourly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cache Ruby Gems
      uses: actions/cache@preview
      with:
        path: vendor/gems
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Install Dependencies
      run: |
        gem install bundler --no-document
        bundle install --jobs 4 --local --deployment
    - name: Do it
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
        INSTAGRAM_TOKEN: ${{ secrets.INSTAGRAM_TOKEN }}
        RACK_ENV: 'production'
      run: bundle exec ruby ./create_post.rb
