name: Scheduled

on:
  schedule:
    - cron: 35 * * * *

jobs:
  hourly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Install Dependencies
      run: |
        gem install bundler --no-document
        bundle install --jobs 4 --local --deployment
    - name: Do it
      run: bundle exec ruby ./create_post.rb